### ISSUE TITLE
npm start crashes on file change

### ISSUE THREAD

**Issue by ianpan870102** [craig-feldman/personal-website-react#1]
After a basic `npm install` and `npm start` to check out the content served in localhost 3000, I noticed that the project **isn't able to render the changes I make to files on-the-fly** -- instead `npm` **crashes whenever I make any changes to any file in the project**. By crashes I meant that `npm start` terminates and returns me back to my terminal prompt.

This is the error that it raised when I tried to edit `/src/App.tsx`:

```none
/home/ianpan/Downloads/personal-website-react/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat '/home/ianpan/Downloads/personal-website-react/src/.#App.tsx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/ianpan/Downloads/personal-website-react/src/.#App.tsx'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! personal-website-react@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the personal-website-react@0.1.0 start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ianpan/.npm/_logs/2020-05-31T04_45_35_809Z-debug.log
```

And this is the content of the log file:

```none
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle personal-website-react@0.1.0~prestart: personal-website-react@0.1.0
6 info lifecycle personal-website-react@0.1.0~start: personal-website-react@0.1.0
7 verbose lifecycle personal-website-react@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle personal-website-react@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ianpan/Downloads/personal-website-react/node_modules/.bin:/home/ianpan/.deno/bin:/home/ianpan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/VSCodium/bin:/mnt/c/Users/bquine/AppData/Local/Programs/Python/Python37-32/Scripts/:/mnt/c/Users/bquine/AppData/Local/Programs/Python/Python37-32/:/mnt/c/Users/bquine/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/bquine/AppData/Local/Programs/Microsoft VS Code/bin:/usr/local/sml/bin
9 verbose lifecycle personal-website-react@0.1.0~start: CWD: /home/ianpan/Downloads/personal-website-react
10 silly lifecycle personal-website-react@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle personal-website-react@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle personal-website-react@0.1.0~start: Failed to exec start script
13 verbose stack Error: personal-website-react@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid personal-website-react@0.1.0
15 verbose cwd /home/ianpan/Downloads/personal-website-react
16 verbose Linux 4.19.104-microsoft-standard
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error personal-website-react@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the personal-website-react@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ianpan870102** [comment]
I have [opened an issue in the npm repo](https://github.com/npm/cli/issues/1365). From a similar [existing issue in Gatsby](https://github.com/gatsbyjs/gatsby/issues/2347), it seems that it's Emacs' auto-saved temp files that are causing trouble.
I can confirm that it's not an issue within the scope of this repo -- hence closing.

**Comment by ianpan870102** [comment]
## [Solved]

Turns out that those aren't auto-saved temp files, but rather symbolic link files.

If you're using Emacs and those `.#` files trouble your development flow, try this option in your `init.el` (Emacs configuration file):

```emacs-lisp
(setq create-lockfiles nil)
```

This will disable the creation of symlink files.

#### References: 
* https://stackoverflow.com/questions/8246483/emacs-how-to-disable-files-creation
* https://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files
